import TanstackProvider from '@/providers/TanstackProvider';
import '../styles/index.css';
import InitAuthProvider from '@/providers/InitAuthProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <TanstackProvider>
          <InitAuthProvider>{children}</InitAuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
